### ISSUE TITLE
show server 500

### ISSUE THREAD

**Issue by praba2210** [Ezhil-Language-Foundation/tamilpesu_us#2] opened 2020-06-17 16:35 UTC
![Screenshot_20200617_220031](https://user-images.githubusercontent.com/32615066/84924714-8d6e3c80-b0e6-11ea-84c9-35cb2e375cb4.png)

**Comment by arcturusannamalai** [comment] 2020-06-17 19:39
duplicate of https://github.com/Ezhil-Language-Foundation/open-tamil/issues/215 - issue is fixed in upstream head. Fix 150f4ed7dfc3f24ede899934cc06a1ed48c18945

**Closed as completed** 2020-11-02 01:24 UTC
Labels: bug, duplicate
